apiVersion: v1
kind: Pod
metadata:
  name: windows-pod
spec:
  containers:
  - name: windows-container
    image: mcr.microsoft.com/windows/servercore:ltsc2022
    command:
      - "cmd"
      - "/c"
      - "echo Hello from Windows Pod && ping localhost -t"
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "512Mi"
  nodeSelector:
    kubernetes.io/os: windows
